---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nemoli.
--- DateTime: 2023/12/15 12:12 上午
---

require("lua_extension")

--- @class ParticleSystem : Component
ParticleSystem = class("ParticleSystem", Component)

function ParticleSystem:ctor()
    ParticleSystem.super.ctor(self)
end

function ParticleSystem:InitCppComponent()
    ---@type Cpp.ParticleSystem
    self.cpp_component_instance_ = Cpp.ParticleSystem()
end

--- 设置Material
--- @param material Material 材质
function ParticleSystem:SetMaterial(material)
    self.cpp_component_instance_:SetMaterial(material:cpp_class_instance())
end

--- 材质
--- @return Material @返回当前使用的材质
function ParticleSystem:material()
    return self.cpp_component_instance_:material()
end

--- 渲染
function ParticleSystem:Render()
    self.cpp_component_instance_:Render()
end