---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nemoli.
--- DateTime: 2023/12/15 12:12 上午
---

require("lua_extension")

--- @class Terrain : Component
Terrain = class("Terrain", Component)

function Terrain:ctor()
    Terrain.super.ctor(self)
end

function Terrain:InitCppComponent()
    ---@type Cpp.Terrain
    self.cpp_component_instance_ = Cpp.Terrain()
end

--- 设置Material
--- @param material Material 材质
function Terrain:SetMaterial(material)
    self.cpp_component_instance_:SetMaterial(material:cpp_class_instance())
end

--- 材质
--- @return Material @返回当前使用的材质
function Terrain:material()
    return self.cpp_component_instance_:material()
end

--- 渲染
function Terrain:Render()
    self.cpp_component_instance_:Render()
end

-- 地形路径
function Terrain:LoadTerrainTexture(terrain_path)
    self.cpp_component_instance_:LoadTerrainTexture(terrain_path)
end