---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nemoli.
--- DateTime: 2023/12/13 11:10 上午
---

require("helpers/debug")
require("app/application")
require("component/game_object")
require("component/transform")
require("game_scene")

function main()
    local go = GameObject.new("GameScene")
    local transform = go:AddComponent(Transform)
    local pos = transform:position()

    go:AddComponent(GameScene)
end